### ISSUE TITLE
Change request

### ISSUE THREAD

**Issue by BernardBekker** [Divanvdb/SUNFIN_app#2]
1. Die huidige dedication maak die nie-ingenieurs kwaad, so kom ons wees maar vriendelik: "The fact that this app is required highlights the importance of first engaging with customers towards clearly defining their basic requirements, before designing a system for them to use. May this understanding spread more widely..."
2. In die "Transaction Account" kolom is daar 'n kode na die kostepunt nommer wat link na 'n beskrywing wat in die aangehegte xls sheet verduidelik word, bv. 1833 in die string "US1-11713-1833-RC-0000-11713>CNF1-0000-0000-US1" sal "SERVICES" wees. Kan jy asb hierdie beskrywing by elke lyn byvoeg aan die einde van die bestaande "Item Category Description", en ook by "Item Description" maar slegs as die veld leeg is.
[Account numbers table.xlsx](https://github.com/user-attachments/files/16905911/Account.numbers.table.xlsx)
3. Kan jy die kolom wydte van kolomme A tot P in die "Processed" xls tab templaat verander na 100 pixels.
4. In die "Processed" tab van die templaat, "untick" die "ignore" filter boksie van die "Project code" kolom sodat die ignored lyne per default nie wys nie.

**Comment by BernardBekker** [comment]
1a. Verander asb die github readme om dieselfde teks te hê as versoek 1. hierbo.
5. Sit asb die instruksie pdf, aangeheg, ook op github en op die app page na die github link: "These *instructions* will explain how the input files are generated."

**Comment by BernardBekker** [comment]
[Guide to Making Sense of SunFin.pdf](https://github.com/user-attachments/files/17013393/Guide.to.Making.Sense.of.SunFin.pdf)

**Comment by Divanvdb** [comment]
Maak so.

Groete
Divan
